# Generated by Django 3.0 on 2020-08-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='time_spent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catagory', to='core.Catagories'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='desc_by_student',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='for_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='core.Student'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='submissiondate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
